version: "3.9"
services:
  server:
    image: rahuldogra/server
    ports:
      - "5000:5000"
    environment:
      - DB_PROD=${DB_PROD}
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    depends_on:
      - server
    volumes:
      - ./node_modules:/client/node_modules
      - ./:/client
    stdin_open: true
    ports:
      - "3000:3000"
